export const INCREMENT = 'INCREMENT'
export const RESET_ITEMS = 'SET_ITEMS'
export const GET_ITEMS = 'GET_ITEMS'
export const ADD_ITEMS = 'ADD_ITEMS'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'
export const CLEAR = 'CLEAR'
